### ISSUE TITLE
Contact EFF

### ISSUE THREAD

**Issue by andresbase** [pipboy96/https-everywhere#1]
Hi @pipboy96 , do you mind contacting me on my email andres at eff.org

Thanks

**Comment by pipboy96** [comment]
@andresbase Can we discuss this here? If we absolutely can't, tell me.

**Comment by pipboy96** [comment]
@andresbase By the way, I found a security vulnerability and I'm not sure whether it's HTTPSE or browser vulnerability. I would like to contact the security team, preferably PGP or OTR encrypted.

**Comment by pipboy96** [comment]
@andresbase Is this GPG key fingerprint correct:

`309A B3E1 766A 0535 56AF  233F 095C B6A6 B3B9 F29C`

**Comment by pipboy96** [comment]
See https://github.com/EFForg/https-everywhere/issues/17640#issuecomment-477825183.
